<?php
$CMS_FIELDS_ALIAS = array(
		'title' => 'text1', 
		'subtitle' => 'text2', 
		'shortdescription' => 'text3', 
		'description' => 'text4', 
		'content' => 'text5',
		'category' => 'text6',
		'subcategory' => 'text7',
		'phone' => 'text8',
		'mobile' => 'text9',
		'fax' => 'text10',
		'email' => 'text11',
		'facebook' => 'text12',
		'twitter' => 'text13',
		'pinterest' => 'text14',
		'linkedIn' => 'text15',
		'instagram' => 'text16',
		'qq' => 'text17',
		'weico' => 'text18',
		'address' => 'text19',
		'website' => 'text20',
		'author' => 'text21',
		'authorbio' => 'text22',
		'url' => 'text23',
		'value' => 'text24',
		'image' => 'text25',
		'gallery' => 'text26',
		'thumbnail' => 'text27',
		'surname' => 'text28',
		'firstname' => 'text29',
		'name' => 'text30',
		'region' => 'text31',
		'destination' => 'text32',
		'excerpts' => 'text33',
		'about' => 'text34',
		'latitude' => 'text35',
		'longitude' => 'text36',
		'default' => 'text37',
		'price' => 'text38',
		'saleprice' => 'text39',
		'features' => 'text40',
		'extra1' => 'text41',
		'extra2' => 'text42',
		'extra3' => 'text43',
		'extra4' => 'text44',
		'extra5' => 'text45',
		'extra6' => 'text46',
		'extra7' => 'text47',
		'extra8' => 'text48',
		'extra9' => 'text49',
		'extra10' => 'text50',
		'startdate' => 'date1', 
		'enddate' => 'date2', 
		'date' => 'date3',
		'firstdate' => 'date4', 
		'lastdate' => 'date5',
		'date1' => 'date6', 
		'date2' => 'date7', 
		'date3' => 'date8', 
		'date4' => 'date9', 
		'date5' => 'date10', 
		'date6' => 'date11', 
		'date7' => 'date12', 
		'date8' => 'date13', 
		'date9' => 'date14', 
		'date10' => 'date15', 
		'date11' => 'date16', 
		'date12' => 'date17', 
		'date13' => 'date18', 
		'date14' => 'date19', 
		'date15' => 'date20'
);

$CMS_FIELDS_META = array(
		'id', 
		'slug', 
		'modelId', 
		'active', 
		'rank', 
		'parentId', 
		'added', 
		'modified'
);

$CMS_WIDGETS = array(
		'email' => 'email',
		'text' => 'text',
		'textarea' => 'textarea',
		'choice' => 'choice',
		'checkbox' => 'checkbox',
		'date' => 'date',
);
?>