<?php

/**
 * 2016-02-07 16:18:29
 */
namespace Pz\DAOs;

class Asset extends \Pz\DAOs\Generated\Asset {

    public function delete()
    {
        $path = HOME_DIR . '/uploads/' . $this->fileLocation;
        if (file_exists($path) && is_file($path)) {
            unlink($path);
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }

}